export const businessTypes: string[] = [
  "Software Company",
  "SaaS",
  "IT Services",
  "Web Development",
  "Mobile App Development",
  "AI & Machine Learning",
  "Cybersecurity",
  "Cloud Services",
  "IT Consulting",
  "Digital Products",
  "Marketing & Creative",
  "Digital Marketing Agency",
  "Advertising Agency",
  "Branding Agency",
  "SEO Agency",
  "Social Media Agency",
  "Graphic Design Studio",
  "Video Production",
  "Content Marketing",
  "Public Relations",
  "Creative Agency",
  "Sales & Consulting",
  "Business Consultant",
  "Sales Agency",
  "B2B Services",
  "Recruitment Agency",
  "HR Consultancy",
  "Financial Consultancy",
  "Legal Consultancy",
  "Accounting Firm",
  "Real Estate",
  "Real Estate Agency",
  "Property Developer",
  "Construction Company",
  "Interior Designer",
  "Architecture Firm",
  "Healthcare",
  "Hospital",
  "Clinic",
  "Dental Clinic",
  "Diagnostic Center",
  "Medical Tourism",
  "Pharmacy",
  "Healthcare Services",
  "Education",
  "School",
  "College",
  "University",
  "Coaching Institute",
  "EdTech Company",
  "Online Course Provider",
  "Training Institute",
  "Hospitality",
  "Hotel",
  "Resort",
  "Homestay",
  "Restaurant",
  "Cafe",
  "Banquet Hall",
  "Catering Service",
  "Travel Agency",
  "Tour Operator",
  "Retail & E-commerce",
  "E-commerce Store",
  "Retail Store",
  "Supermarket",
  "Electronics Store",
  "Fashion & Apparel",
  "Jewelry Store",
  "Furniture Store",
  "Grocery Store",
  "Manufacturing",
  "Manufacturing Company",
  "Industrial Equipment",
  "Automotive",
  "Textile",
  "Chemical",
  "Electronics Manufacturing",
  "Packaging",
  "Finance",
  "Bank",
  "Insurance",
  "FinTech",
  "Investment Firm",
  "Loan Provider",
  "Tax Consultant",
  "Logistics",
  "Logistics Company",
  "Courier Service",
  "Transportation",
  "Warehousing",
  "Supply Chain",
  "Media",
  "News Agency",
  "Publishing",
  "Printing Press",
  "Radio",
  "Television",
  "Podcast Network",
  "Events",
  "Event Management",
  "Wedding Planner",
  "Exhibition Organizer",
  "Conference Organizer",
  "Beauty & Wellness",
  "Salon",
  "Spa",
  "Gym",
  "Fitness Center",
  "Yoga Studio",
  "Wellness Center",
  "Non-Profit",
  "NGO",
  "Charity",
  "Trust",
  "Government Organization",
  "Professional Services",
  "Freelancer",
  "Startup",
  "Small Business",
  "Enterprise",
  "Franchise",
  "Distributor",
  "Wholesaler",
  "Other",
];
